---
### Creating New VPC
- hosts: 172.31.6.7
  connection: local
  gather_facts: false
  user: ubuntu
  tasks:
    # Creating the VPC in specified region and saving the VPC Id value in new variable
    - name:               Create VPC
      ec2_vpc_net:
        name:             "ansible"
        cidr_block:       "10.0.0.0/16"
        region:           "us-east-2"
        state:            "present"
     
